language: node_js
node_js:
  - stable

cache:
  directories:
    - ~/.yarn-cache
    - node_modules
    - www/node_modules

jobs:
  include:
    - stage: Chrome
      env: BROWSER=ChromeCi
      addons:
        chrome: stable
    - stage: Firefox
      env: BROWSER=Firefox
      addons:
        firefox: latest

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0

install:
  - yarn bootstrap

after_success:
  - if ([ ! -z "$TRAVIS_TAG" ]); then
    yarn build-docs
  fi
  - yarn codecov

branches:
  only:
    - master

deploy:
  provider: pages
  repo: react-bootstrap/react-bootstrap.github.io
  local-dir: www/public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    tags: true
